/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rabbitsvsfoxes;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.border.BevelBorder;

/**
 *
 * @author Georgi
 */
public class RVFGui extends javax.swing.JFrame {

    private final ImageIcon grassIcon
            = new ImageIcon("images/grass.png", "Grass icon");
    ;
    private JPanel panel1;
    private int size = 30;
    private List<JLabel> labels;
    private Set<Agent> agents;
    private Set<EnvironmentObject> envObjects;
    private FoxAgent fox1;
    private RabbitAgent rabbit1;
    private RVFGui env = this;
    private JLabel foxLabel;
    private Color backgroundC = Color.decode("#169B08");

    public RVFGui() {
        initComponents();//generated method
        initialiseVariables();
        drawField();

        //fox1 = new FoxAgent(0, 0);
        //rabbit1 = new RabbitAgent(0,0);

        //foxLabel = this.getLabel(fox1.getPositionX(), fox1.getPositionY());
        //foxLabel.setIcon(fox1.getIcon());

        // JLabel rabbitLabel=this.getLabel(0, 0);
        // rabbitLabel.setIcon(rabbit1.getIcon());
        ActionListener listener = (ActionEvent event) -> {
            startMoving();
        };
        Timer displayTimer = new Timer(500, listener);
        //displayTimer.start();

        this.setContentPane(panel1);
    }

    private void initialiseVariables() {
        this.agents = new LinkedHashSet();
        this.envObjects = new LinkedHashSet();
        labels = new ArrayList<>();
        panel1 = new JPanel(new GridLayout(size, size));

        for (int i = 0; i < 6; i++) {
            this.agents.add(new RabbitAgent(randomRange(0, size - 1), randomRange(0, size - 1)));
            this.agents.add(new FoxAgent(randomRange(0, size - 1), randomRange(0, size - 1)));
        }
    }

    private void drawField() {
        for (int i = 0; i < size; i++) {
            for (int j = 0; j < size; j++) {
                JLabel l = new JLabel("", JLabel.CENTER);
                l.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
                l.setFont(l.getFont().deriveFont(12f));
                l.setBackground(backgroundC);
                l.setIcon(grassIcon);
                l.setOpaque(true);
                panel1.add(l);
                labels.add(l);
            }
        }
        for (Agent a : agents) {
            JLabel curLabel;
            curLabel = this.getLabel(a.getPositionX(), a.getPositionY());
            curLabel.setIcon(a.getIcon());
        }
    }

    public int randomRange(int min, int max) {
        int range = Math.abs(max - min) + 1;
        return (int) (Math.random() * range) + (min <= max ? min : max);
    }

    public void addAgent(Agent a) {
        addEnvironmentObject(a);
    }

    public void removeAgent(Agent a) {
        removeEnvironmentObject(a);
    }

    public void addEnvironmentObject(EnvironmentObject eo) {

    }

    public void removeEnvironmentObject(EnvironmentObject eo) {

    }

    public void step() {

    }

    public JLabel getLabel(int x, int y) {
        int index = y * size + x;
        return labels.get(index);
    }

    private void setLabel(int r, int c, JLabel newLabel) {
        int index = r * size + c;
        labels.set(index, newLabel);
    }

    private void startMoving() {
        int x1 = fox1.getPositionX();
        int y1 = fox1.getPositionY();
        double direction = Math.random();
        if (direction < 0.25) {
            x1++;
        } else if (direction < 0.5) {
            y1--;
        } else if (direction < 0.75) {
            x1--;
        } else {
            y1++;
        }
        if (x1 >= size) {
            x1--;

        } else if (x1 < 0) {
            x1++;
        }
        if (y1 >= size) {
            y1--;

        } else if (y1 < 0) {
            y1++;
        }
        fox1.setPosition(x1, y1);
        foxLabel.setIcon(grassIcon);
        foxLabel = env.getLabel(x1, y1);
        foxLabel.setIcon(fox1.getIcon());
    }

    public void visualise() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RVFGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RVFGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RVFGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RVFGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RVFGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
